<main id="home" class="py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Latest posts</h2>
    <ul class="row mt-5">
        <?php foreach ($data['items'] as $key => $data) {  ?>

            <li class="col-4 my-2">
                <article class="card">
                    <header class="card-body">
                        <h3 class="h5 card-title"><?= $data->getTitle()  ?></h3>
                        <h4 class="h6 card-subtitle mb-2 text-body-secondary"><?php foreach ($data->getCategory() as $key => $value) {
                                                                                    echo $value->getTitle();
                                                                                } ?></h4>
                    </header>
                    <section class="card-body">
                        <p class="card-text"><?= $data->getExcerpt()  ?></p>
                        <a href="index.php?route=post&post_id=<?= $data->getId() ?>" class="btn btn-primary">Post Link</a>

                    </section>
                </article>
            </li>
        <?php } ?>
    </ul>
</main>