<main id="login" class="container py-5 px-3">
    <h1 class="mb-5"><?= $this->translator->translate("blog_title") ?></h1>

    <h2 class="mt-5"><?= $this->translator->translate("nav_login_link") ?></h2>

    <form action="index.php?route=check-login" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="<?= $_SESSION['csrf_token'] ?>" />
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("login_email_label") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                <?= $this->translator->translate("login_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("nav_login_link") ?></button>
        </fieldset>
    </form>
</main>